### ISSUE TITLE
Organization Page

### ISSUE THREAD

**Issue by fakhrihawari** [drfaustusfade/ngm-reportDesk#25]
Switch Button

https://user-images.githubusercontent.com/12655589/103966023-97927e00-5191-11eb-9606-f576a0933f6d.mp4

Mock Up
![192 168 33 16_desk_ (33)](https://user-images.githubusercontent.com/12655589/103866251-0f13cf00-50f8-11eb-92eb-f1df708908c0.png)

**Comment by drfaustusfade** [comment]
Alright, almost there, 
- I noticed now that better instead of using button _Go To Org_, that on many elements is visually heavy, maybe small icon in the corner, or better to have organization name highlighted in blue with a link
- table list for comma-separated might be better without cards
- cards for cluster and # of active organizations are too wide, maybe to check to leave only organizations details with cards

Organization Profile
- profile should be per country, + admin title 
- \+ upper right corner Joined: \<Date>
- details dashboard button links look a bit heavy on the card, maybe to check how that would look with other materialize elements like a collection, a number of dashboards can change, but buttons are restricted
![chrome_bSLyKeDb7v](https://user-images.githubusercontent.com/29349472/104159113-5eb20d80-540c-11eb-9639-af9d59a37fba.png)
 - For contact alright, but on edit, there should be a possibility to select from the organization users
-  Description maybe edit switch icon to change to edit mode for admin roles
- update(save) button for admin roles

**Comment by fakhrihawari** [comment]
![Uploading 192.168.33.16_desk_ (34).png…]()

**Comment by fakhrihawari** [comment]
<img width="1280" alt="Screen Shot 2021-01-11 at 16 42 50" src="https://user-images.githubusercontent.com/12655589/104165541-1b679700-542c-11eb-9d2e-49c36d349017.png">
<img width="1283" alt="Screen Shot 2021-01-11 at 16 42 43" src="https://user-images.githubusercontent.com/12655589/104165550-1dc9f100-542c-11eb-9c08-846b9230bf1e.png">

**Comment by fakhrihawari** [comment]
![192 168 33 16_desk_ (35)](https://user-images.githubusercontent.com/12655589/104165961-a3e63780-542c-11eb-875b-4e14c5fe6ef3.png)

**Comment by fakhrihawari** [comment]
is it like that ?

**Comment by drfaustusfade** [comment]
- comma-separated list is alright, please set is as primary view, so that admins could see the short overview right on
- for card org details view if some alternative for cluster and # of orgs is possible, right now with cards it's disproportional to org details cards
- rename _Organization Active to Active Organizations_, _Contact Organizations to Organization Contacts_, and on table view to _Organizations_ 
- highlight just organization name in blue, email should be easy to copy 
- rename List Organizations with Activities to Organizations Provided Services
- (profile) can you also try to put dashboard collection as a separate card, a bit cramped like that

**Comment by fakhrihawari** [comment]
<img width="1235" alt="Screen Shot 2021-01-12 at 10 04 01" src="https://user-images.githubusercontent.com/12655589/104264100-8f9e4b00-54bd-11eb-877b-f0755a249382.png">
<img width="1249" alt="Screen Shot 2021-01-12 at 10 03 51" src="https://user-images.githubusercontent.com/12655589/104264112-95942c00-54bd-11eb-8017-a819bdfc4836.png">


Is it okay ?

**Comment by fakhrihawari** [comment]
![192 168 33 16_desk_ (36)](https://user-images.githubusercontent.com/12655589/104264681-ab562100-54be-11eb-9ca1-866a9948e7a0.png)

**Comment by drfaustusfade** [comment]
alright, nice, nearly there
- for organizations provided services, if it is possible to centre org/email/phone on the card 
- for organizations provided services, there is an idea to have only organization details without disaggregation by cluster and #, so that not to duplicate table view, in that way it will nicer, up to the need to check details, and will much compact
- organizations profile sorry i mean dashboards collection card (with Dashboards header title) without the base card, so that not to have pyramid effect when there is between cards big margins
- organization profile, edit button has big margin to the bottom of cards, maybe to reduce it to look nicer, or to try having on the label with the edit icon so that to have fewer elements

**Comment by fakhrihawari** [comment]
point 1  what do you mean centre?  vertically?
point 2 can you give me an example

**Comment by fakhrihawari** [comment]
point 3
<img width="839" alt="Screen Shot 2021-01-12 at 13 48 39" src="https://user-images.githubusercontent.com/12655589/104279450-e6ffe380-54dc-11eb-968c-ed5e7032aa3b.png">

**Comment by drfaustusfade** [comment]
point 1 vertically 
point 2 on card view having just Organizations Contacts column with card details of all reported organizations
point 3 how would it look if the collection would be on a card without dashboard label with small margins

**Comment by fakhrihawari** [comment]
point 1 , 2

https://user-images.githubusercontent.com/12655589/104284891-5da0df00-54e5-11eb-9d2f-83ece4409bc2.mp4

remove duplicate organization ? or keep them, coz in the organization for each cluster, the reporter is different

**Comment by fakhrihawari** [comment]
point3
<img width="839" alt="Screen Shot 2021-01-12 at 14 57 26" src="https://user-images.githubusercontent.com/12655589/104285667-883f6780-54e6-11eb-93df-e9de5990fb09.png">

**Comment by drfaustusfade** [comment]
> point 1 , 2
> 
>  2demo.mp4 
> remove duplicate organization ? or keep them, coz in the organization for each cluster, the reporter is different

very good point, more generally the there could be multiple reporters per cluster, it that case putting a label or title on each cluster section might work

**Comment by drfaustusfade** [comment]
> point3
> <img alt="Screen Shot 2021-01-12 at 14 57 26" width="839" src="https://user-images.githubusercontent.com/12655589/104285667-883f6780-54e6-11eb-93df-e9de5990fb09.png">

alright, maybe also putting some heading with _Pages_

**Comment by fakhrihawari** [comment]
<img width="1264" alt="Screen Shot 2021-01-12 at 15 20 14" src="https://user-images.githubusercontent.com/12655589/104287899-b2465900-54e9-11eb-9708-7c8d9a0641d4.png">

**Comment by drfaustusfade** [comment]
cool, maybe just one of those or putting cluster under organization name, 
also, i just noticed if we could please put user full name before email

**Comment by fakhrihawari** [comment]
<img width="846" alt="Screen Shot 2021-01-12 at 15 52 45" src="https://user-images.githubusercontent.com/12655589/104291856-ab6e1500-54ee-11eb-86c5-a6f763b3d471.png">

**Comment by drfaustusfade** [comment]
seems the last screenshot not loaded

**Comment by drfaustusfade** [comment]
alright, looks good

**Comment by fakhrihawari** [comment]
<img width="1248" alt="Screen Shot 2021-01-12 at 16 20 52" src="https://user-images.githubusercontent.com/12655589/104294757-2c7adb80-54f2-11eb-9ea7-7b4fbfd92ef7.png">

**Comment by drfaustusfade** [comment]
ok, i think good to go like that

**Comment by fakhrihawari** [comment]
Link for PR
https://github.com/drfaustusfade/ngm-reportEngine/pull/15
https://github.com/drfaustusfade/ngm-reportHub/pull/54

**Comment by drfaustusfade** [comment]
- query beneficiairies by reporting_period, for monthly reporting reporting_period is first day of month, beneficiary record has that value, so that to show what was reporting on filtered month, not everything from project
- add to menu MY HOME > MY ORGANIZATION
- open organization details in new window and hide temporary navigation back on organizations page

**Comment by fakhrihawari** [comment]
Point 1 what do you mean?

**Comment by fakhrihawari** [comment]
Updated

**Comment by fakhrihawari** [comment]
<img width="1248" alt="Screen Shot 2021-01-13 at 16 52 50" src="https://user-images.githubusercontent.com/12655589/104436286-00c62700-55c0-11eb-86b2-c151000614c6.png">

**Comment by drfaustusfade** [comment]
- \# of users statistic should be per current country scope of that organization

**Comment by drfaustusfade** [comment]
- description should switch between edit and view mode, so that not to show both

**Comment by drfaustusfade** [comment]
separate task/pull request
- [ ] country organization list ( to quickly check organizations present in the country, main users Cluster and Country Admins )
Title : AF | Organization
download: list of organizations
table: Organization | Organization (Abrv) | Type | Joined | Last Reported | Clusters | Focal Point Name | Email | Phone | (Link to organization page)
filter: by Type | Cluster
the cluster based on organization-defined organization, ( that will be used for Cluster filter to get Last Reported )
roles: excluding User, Org ( that is closed access for now )

**Comment by fakhrihawari** [comment]
> > separate task/pull request
> > 
> > * [ ]   country organization list ( to quickly check organizations present in the country, main users Cluster and Country Admins )
> >   Title : AF | Organization
> >   download: list of organizations
> >   table: Organization | Organization (Abrv) | Type | Joined | Last Reported | Clusters | Focal Point Name | Email | Phone | (Link to organization page)
> >   filter: by Type | Cluster
> >   the cluster based on organization-defined organization, ( that will be used for Cluster filter to get Last Reported )
> >   roles: excluding User, Org ( that is closed access for now )

**Comment by fakhrihawari** [comment]
> separate task/pull request
> 
> * [ ]  country organization list ( to quickly check organizations present in the country, main users Cluster and Country Admins )
>   Title : AF | Organization
>   download: list of organizations
>   table: Organization | Organization (Abrv) | Type | Joined | Last Reported | Clusters | Focal Point Name | Email | Phone | (Link to organization page)
>   filter: by Type | Cluster
>   the cluster based on organization-defined organization, ( that will be used for Cluster filter to get Last Reported )
>   roles: excluding User, Org ( that is closed access for now )

Is just for AF or all country too? if for all country need to put country filter too

**Comment by drfaustusfade** [comment]
the main use for the page is per country, not required but the country filter can be put also

> > separate task/pull request
> > 
> > * [ ]   country organization list ( to quickly check organizations present in the country, main users Cluster and Country Admins )
> >   Title : AF | Organization
> >   download: list of organizations
> >   table: Organization | Organization (Abrv) | Type | Joined | Last Reported | Clusters | Focal Point Name | Email | Phone | (Link to organization page)
> >   filter: by Type | Cluster
> >   the cluster based on organization-defined organization, ( that will be used for Cluster filter to get Last Reported )
> >   roles: excluding User, Org ( that is closed access for now )
> 
> Is just for AF or all country too? if for all country need to put country filter too

not required, the main page use is per country but can be put also

**Comment by fakhrihawari** [comment]
> the main use for the page is per country, not required but the country filter can be put also
> 
> > > separate task/pull request
> > > 
> > > * [ ]    country organization list ( to quickly check organizations present in the country, main users Cluster and Country Admins )
> > >   Title : AF | Organization
> > >   download: list of organizations
> > >   table: Organization | Organization (Abrv) | Type | Joined | Last Reported | Clusters | Focal Point Name | Email | Phone | (Link to organization page)
> > >   filter: by Type | Cluster
> > >   the cluster based on organization-defined organization, ( that will be used for Cluster filter to get Last Reported )
> > >   roles: excluding User, Org ( that is closed access for now )
> > 
> > 
> > Is just for AF or all country too? if for all country need to put country filter too
> 
> not required, the main page use is per country but can be put also

the clusters attribute in organization exist? or its cluster from last report?

**Comment by fakhrihawari** [comment]
<img width="1679" alt="Screen Shot 2021-01-14 at 14 35 24" src="https://user-images.githubusercontent.com/12655589/104558687-c4550280-5675-11eb-8f55-e7c9f40aa64a.png">

**Comment by drfaustusfade** [comment]
> > the main use for the page is per country, not required but the country filter can be put also
> > > > separate task/pull request
> > > > 
> > > > * [ ]     country organization list ( to quickly check organizations present in the country, main users Cluster and Country Admins )
> > > >   Title : AF | Organization
> > > >   download: list of organizations
> > > >   table: Organization | Organization (Abrv) | Type | Joined | Last Reported | Clusters | Focal Point Name | Email | Phone | (Link to organization page)
> > > >   filter: by Type | Cluster
> > > >   the cluster based on organization-defined organization, ( that will be used for Cluster filter to get Last Reported )
> > > >   roles: excluding User, Org ( that is closed access for now )
> > > 
> > > 
> > > Is just for AF or all country too? if for all country need to put country filter too
> > 
> > 
> > not required, the main page use is per country but can be put also
> 
> the clusters attribute in the organization exist? or its cluster from the last report?

clusters from organization array attribute ( so that organizations define which clusters currently they are affiliated )
if all clusters ( last reported beneficiaries record from that organization with their clusters ( if no yet clusters defined then any organization record )
if filtered cluster ( last reported cluster beneficiaries record from that organization )

**Comment by fakhrihawari** [comment]
Update organization lists
<img width="303" alt="Screen Shot 2021-01-15 at 16 06 32" src="https://user-images.githubusercontent.com/12655589/104704793-af4aa300-574b-11eb-82f1-3ce21c24de2a.png">
<img width="1611" alt="Screen Shot 2021-01-15 at 16 06 21" src="https://user-images.githubusercontent.com/12655589/104704807-b2459380-574b-11eb-9fe3-b4a7e8d55eb2.png">

**Comment by drfaustusfade** [comment]
alright,
also, in the menu let's put temporary under dashboards and not under my home
Organization => Organizations
Cluster => Clusters

**Comment by fakhrihawari** [comment]
Organization => Organizations
Cluster => Clusters
what is that ?
filter?

**Comment by drfaustusfade** [comment]
that's spelling correction to use the plural form in title and table column name

**Comment by fakhrihawari** [comment]
<img width="1667" alt="Screen Shot 2021-01-15 at 16 32 31" src="https://user-images.githubusercontent.com/12655589/104707683-4fee9200-574f-11eb-9bd3-c3a666170335.png">

and the download is csv file

**Comment by drfaustusfade** [comment]
ok, well done

**Comment by fakhrihawari** [comment]
okay I will make PR

link
https://github.com/drfaustusfade/ngm-reportEngine/pull/16
https://github.com/drfaustusfade/ngm-reportHub/pull/65

**Comment by drfaustusfade** [comment]
I think would be also nice to have type in quick table filtering for organization list and maybe to try having 100 list elements rather than 10

**Comment by fakhrihawari** [comment]
100 is too long, i propose 20 or 25

**Comment by drfaustusfade** [comment]
alright

**Comment by fakhrihawari** [comment]
Update:
https://github.com/drfaustusfade/ngm-reportHub/pull/72

**Comment by drfaustusfade** [comment]
thanks
on /organization-contact/... there was an user error
TypeError: Cannot read property 'roles' of undefined
```
TypeError: Cannot read property 'roles' of undefined undefined
logger: console
arguments: [{"message":"Cannot read property 'roles' of undefined","name":"TypeError","stack":"TypeError: Cannot read property 'roles' of undefined\n    at Object.canEdit...
```

**Comment by fakhrihawari** [comment]
Ok, already fix it:
https://github.com/drfaustusfade/ngm-reportHub/pull/72/files
